import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vitest/config';
// @ts-expect-error -- plain JS module, shared with front/vite.config.ts and the arch lint.
import { aliases } from './scripts/aliases.mjs';

export default defineConfig({
    plugins: [vue()],
    // The same map the app builds with, so a test resolves an import as the browser will.
    resolve: { alias: aliases },
    test: {
        globals: true,
        // happy-dom rather than jsdom: far faster to start, and nothing here needs jsdom's
        // fuller browser surface.
        environment: 'happy-dom',
        setupFiles: ['./tests/setup.ts'],
        env: {
            // front/src/backend/index.ts refuses to load without this, and any component tree
            // deep enough pulls it in. The client is built but never called — anything that
            // would reach the network fails loudly, which is the cue to mock that feature's api.
            VITE_API_URL: 'http://pocketbase.test',
        },
        include: [
            'front/src/**/*.spec.ts',
            'packages/*/src/**/*.spec.ts',
        ],
        coverage: {
            provider: 'v8',
            reporter: ['text-summary', 'html'],
            include: ['front/src/**', 'packages/*/src/**'],
            exclude: [
                '**/*.spec.ts',
                // Generated by pocketbase-typegen; regenerated, never hand-edited.
                'front/src/backend/schema.g.ts',
                // Composition roots: wiring only, and what they wire is the real backend.
                'front/src/app/main.ts',
                'front/src/backend/index.ts',
                '**/*.d.ts',
            ],
        },
    },
});
