import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vitest/config';
// @ts-expect-error -- plain JS module, shared with front/vite.config.ts and the arch lint.
import { aliases } from './scripts/aliases.mjs';

export default defineConfig({
    plugins: [vue()],
    // The same map the app builds with: a test resolves an import exactly as the browser will.
    resolve: { alias: aliases },
    test: {
        globals: true,
        // happy-dom rather than jsdom: the suite is component-level, and it starts in a
        // fraction of the time. Nothing here needs jsdom's fuller browser surface.
        environment: 'happy-dom',
        setupFiles: ['./tests/setup.ts'],
        include: [
            'front/src/**/*.spec.ts',
            'packages/*/src/**/*.spec.ts',
            'tests/**/*.spec.ts',
        ],
        coverage: {
            provider: 'v8',
            reporter: ['text-summary', 'html'],
            include: ['front/src/**', 'packages/*/src/**'],
            exclude: [
                '**/*.spec.ts',
                // Generated by pocketbase-typegen; regenerated, never hand-edited.
                'front/src/backend/schema.g.ts',
                // Composition root: wiring only, and what it wires is the real backend.
                'front/src/app/main.ts',
                'front/src/backend/index.ts',
                '**/*.d.ts',
            ],
        },
    },
});
